name: release code through curl
on: [push]
jobs:
  job_curl:
    runs-on: [ubuntu-latest]
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: get list of files
        run: ls -l
      - run: env
        name: display env
      - name: get env vars
        env:
          GITHUB_REF: ${{github_ref}}
        run: echo ${{github_ref}}





