name: release-github-actions
on:
  push:
    tags:
      - "*"

jobs:
  ci-server:
    uses: devps23/reuse-github-actions/.github/workflows/release.yml@main
    with:
      project-name: expense-backend
    secrets: inherit