name: release code through curl
on: [push]
jobs:
  backend-curl:
    uses: devps23/reuse-github-actions/.github/workflows/release_curl.yml@v1
    with:
      project-name: expense-backend
      release_artifact_file: "*.js json schema VERSION"
    secrets: inherit








