name: release-github-actions
on:
  push:
    tags:
      - "*"

jobs:
  ci-server:
    runs-on: ubuntu-latest
    steps:
       - run: echo Hello world
         name: display mssg
#    uses: devps23/reuse-github-actions/.github/workflows/release.yml@main
#    with:
#      project-name: expense-backend
#    secrets: inherit