name: release code through curl
on: [push]
jobs:
  ci-server:
    uses: devps23/reuse-github-actions/.github/workflows/release_curl.yml@main
    with:
      project-name: expense-backend
      release_archive_file: "*.js package.json schema"
    secrets: inherit








